--------------------------------------------------------
--  File created - Tuesday-August-12-2025   
--------------------------------------------------------
REM INSERTING into DBO.MES_BILL_OF_MATERIAL
 CREATE TABLE "DBO"."MES_BILL_OF_MATERIAL" 
   (	"PRODUCT_ID" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"PRODUCT_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PRODUCT_FAMILY_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"UNIT_OF_MEASURE" VARCHAR2(10 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
SET DEFINE OFF;
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('11000000001','STEEL ORE','ORE','KG');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('11000000002','IRON ORE','ORE','KG');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('11000000003','COPPER ORE','ORE','KG');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000011','1" STEEL GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000012','2" STEEL GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000021','1" IRON GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000022','2" IRON GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000023','3" IRON GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000031','1" COPPER GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000032','2" COPPER GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000033','3" COPPER GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('44000000013','3" STEEL GEAR','GEAR','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000111','3-PACK 1" STEEL GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000112','3-PACK 2" STEEL GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000113','3-PACK 3" STEEL GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000121','3-PACK 1" IRON GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000122','3-PACK 2" IRON GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000123','3-PACK 3" IRON GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000131','3-PACK 1" COPPER GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000132','3-PACK 2" COPPER GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000133','3-PACK 3" COPPER GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000231','COMBO PACK COPPER GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000221','COMBO PACK IRON GEAR','FINAL','QTY');
Insert into DBO.MES_BILL_OF_MATERIAL (PRODUCT_ID,PRODUCT_DESC,PRODUCT_FAMILY_CODE,UNIT_OF_MEASURE) values ('70000000211','COMBO PACK STEEL GEAR','FINAL','QTY');
